TARGET = nice_vector_matrix_multiplication

HBIRD_SDK_ROOT = /home/liqb365/Workarea/coding/Hardware/hbird-sdk

SRCDIRS = .

INCDIRS = ../include

COMMON_FLAGS := -O0

include $(HBIRD_SDK_ROOT)/Build/Makefile.base
